### ISSUE TITLE
Release of AliOpenKG and eBay

### ISSUE THREAD

**Issue by ysunbp** [jingcshi/ICON#1]
Hello! Thank you for your amazing work! I wonder if you can release the AliOpenKG and eBay taxonomies used in your paper? It seems that there is only google taxonomy in the data folder.

**Comment by jingcshi** [comment]
Sorry that the eBay taxonomy is commercial and cannot be disclosed. I don't have the AliOpenKG taxonomy in json right now but the same data in a different format can be found [here](https://drive.google.com/drive/folders/1HBxaNTjNh7JttlwC2i5hdI5bhsbhsCB3?usp=sharing). TBox is the taxonomy while ABox is a collection of items associated with the concepts in TBox.
